#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

# settings

    # flag to enable computations in parallel mode
    parallel=true


#------------------------------------------------------------------------------

restore0Dir

#[ -d constant/polyMesh ] || cp -rf constant/polyMesh.orig constant/polyMesh

runApplication blockMesh

if [ "$parallel" = true ]
then

    runApplication decomposePar

    # runParallel on its own does not stop the script when the solver diverges
    # or is killed -- Allrun would fall through to reconstructPar and exit 0,
    # so the app would log a crashed run as finished successfully.
    runParallel $(getApplication) || exit 1

    runApplication reconstructPar

    #runApplication foamMonitor postProcessing/forceCoeffs/0/coefficient.dat


else


    runApplication $(getApplication) || exit 1

fi


#------------------------------------------------------------------------------
